title: Viaduct Echo
description: Stockport news through the arches
url: https://viaductecho.info
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:categories/:year/:month/:day/:title/