title: Viaduct Echo
description: Stockport news under the arches
url: https://viaductecho.info
baseurl: ""
timezone: Europe/London

remote_theme: wowthemesnet/affiliates-jekyll-theme

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

permalink: "/:title/"
paginate: 10                 
paginate_path: "/page:num/"  

logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"

authors:
  archie:
    name: "Archie Echo"
    display_name: "Archie"
    bio: "Chief Editor"
    avatar: "assets/images/avatar.png"
    email: hello@viaductecho.info
    web: https://viaductecho.info

defaults:
  - scope: {type: posts}
    values: {layout: post, comments: true}

sass:
  style: compressed
  load_paths:
    - _sass
    - assets/css